function Hd = DSP_HilbAuto
%DSP_HILBAUTO Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.10 and Signal Processing Toolbox 8.6.
% Generated on: 17-Feb-2022 22:19:14

% FIR least-squares Hilbert transformer filter designed using the FIRLS
% function.

% All frequency values are in Hz.
Fs = 32000;  % Sampling Frequency

N = 90;          % Order
F = [50 14500];  % Frequency Vector
A = [1 1];       % Amplitude Vector
W = 50;          % Weight Vector

b  = firls(N, F/(Fs/2), A, W, 'hilbert');
Hd = dfilt.dffir(b);

[Coeffs, A] = impz(Hd);

FID = fopen('RyanColon_HilCoeff14.txt','w');

if FID > 0
    fprintf(FID, "Ryan Colon, Hilbert Transform Filter, Attempt 14 (Book)\n");
    for i = 1:(length(Coeffs)-1)
        if mod(i,2) == 1
            fprintf(FID, '%.14f\n', 0.0);
        else
            fprintf(FID, '%.14f\n', Coeffs(i));
        end
    end
    %fprintf(FID, '%.14f', Coeffs(length(Coeffs)));
    fprintf(FID, '%.14f', 0.0);
    fclose(FID);
end

% [EOF]
